Fix nonrobust tests
mullvad/mullvadvpn-app-tests pull request #105
Opened 2023-08-25 14:11 UTC by dlon

A couple of small changes:
* `test_content_blockers` fails once in a blue moon. Likely because `set_dns_options` isn't guaranteed to take effect *immediately*.
* Sleep for a while after restarting the daemon. The UDS isn't necessarily immediately available as soon as the service is running.

2023-08-25 15:27 UTC, MarkusPettersson98 requested changes
Nice! I've noticed these things failing from time to time, so it's nice to see better fault tolerance :)

See my comments, they are fairly minor. Good job!

> Reviewed 5 of 5 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/105#-:-NchG5yC5tnWbb71rViy:bm2ex4j)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`test-manager/src/tests/dns.rs` line 590 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/105#-NchAVGEEmtaOvaguGqA:-NchAVGEEmtaOvaguGqB:bhi8tw4) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/cf7e0c37dd4d4716b38c813292c1d2e9401abdd4/test-manager/src/tests/dns.rs#L590)):*
> ```XML
>         NONCE += 2;
>         (i, i + 1)
>     };
> ```

I suggest that we get rid of the `unsafe` block while we are here.
It would be fairly trivial to emulate the desired behavior with a generator(isch) using a range, i.e.:

```rust
    let mut nonce = {
        let mut seed = (0..).step_by(3);
        move || seed.next().unwrap()
    };
```

Whenver we call `nonce()`, we get a unique value back from the sequence `0, 3, 6 ..`, to mimick `nonce1` and `nonce2`.

With this, we could replace

```rust
    // resolve a "random" domain name to prevent caching
    static mut NONCE: usize = 0;

    let (nonce1, nonce2) = unsafe {
        let i = NONCE;
        NONCE += 2;
        (i, i + 1)
    };

    let rpc_client = rpc.clone();
    let handle = tokio::spawn(async move {
        let _ = rpc_client
            .resolve_hostname(format!("test{nonce1}.mullvad.net"))
            .await;

        // Retry just to be sure. DNS config change may not take effect immediately.
        tokio::time::sleep(Duration::from_secs(2)).await;
        let _ = rpc_client
            .resolve_hostname(format!("test{nonce2}.mullvad.net"))
            .await;
    });

```

with

```rust
    // resolve a "random" domain name to prevent caching
    let mut nonce = {
        let mut nums = (0..).step_by(3);
        move || nums.next().unwrap()
    };

    let rpc_client = rpc.clone();
    tokio::spawn(async move {
        // Retry multiple times just to be sure. DNS config change may not take effect immediately.
        for _ in 1..=2 {
            let _ = rpc_client
                .resolve_hostname(format!("test{}.mullvad.net", nonce()))
                .await;
            tokio::time::sleep(Duration::from_secs(2)).await;
        }
    });

```

What do you think? :blush:

To be perfectly honest, one could get away with using the loop-variable as a seed for the nonce :sweat_smile: 



_Code quote:_
```XML
    static mut NONCE: usize = 0;

    let (nonce1, nonce2) = unsafe {
        let i = NONCE;
        NONCE += 2;
        (i, i + 1)
    };
```
___
*[`test-rpc/src/client.rs` line 145 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/105#-NchH--W37NT8XUE4GFD:-NchH--W37NT8XUE4GFE:b-ji5vme) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/9a7e4da4fc2d43b2952db89b82dc77f12f38d9f4/test-rpc/src/client.rs#L145)):*
> ```XML
>             tokio::time::sleep(POLL_INTERVAL).await;
>         }
>     }
> ```

Using a regular `for`-loop leads to less stateful code (i.e. less to track in your head while reading the code):

```rust
    async fn mullvad_daemon_wait_for_state(
        self,
        accept_state_fn: impl Fn(ServiceStatus) -> bool,,
    ) -> Result<(), test_rpc::Error> {
        const MAX_ATTEMPTS: usize = 10;
        const POLL_INTERVAL: Duration = Duration::from_secs(3);
        for _ in 0..MAX_ATTEMPTS {
            let last_state = self.mullvad_daemon_get_status().await?;
            // A regular `if` would also work, `match` was just shorter 
            match accept_state_fn(last_state) {
                true => return Ok(()),
                false => tokio::time::sleep(POLL_INTERVAL).await,
            }
        }
        Err(Error::Timeout)
    }
```

Also, would there be any point in returning the accepted state? Worst case the caller just has to drop it :shrug: 



_Code quote:_
```XML
    pub async fn mullvad_daemon_wait_for_state(
        &self,
        accept_state_fn: impl Fn(ServiceStatus) -> bool,
    ) -> Result<(), Error> {
        const MAX_ATTEMPTS: usize = 10;
        const POLL_INTERVAL: Duration = Duration::from_secs(3);

        let mut attempt = 0;

        loop {
            let last_state = self.mullvad_daemon_get_status().await?;
            if accept_state_fn(last_state) {
                break Ok(());
            }

            attempt += 1;
            if attempt >= MAX_ATTEMPTS {
                break Err(Error::Timeout);
            }

            tokio::time::sleep(POLL_INTERVAL).await;
        }
    }
```


<!-- Sent from Reviewable.io -->

2023-08-25 16:14 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/105)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`test-manager/src/tests/dns.rs` line 590 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/105#-NchAVGEEmtaOvaguGqA:-NchQzdGD3CScBC3czvm:b-20sq1b) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/cf7e0c37dd4d4716b38c813292c1d2e9401abdd4/test-manager/src/tests/dns.rs#L590)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

I suggest that we get rid of the `unsafe` block while we are here.
It would be fairly trivial to emulate the desired behavior with a generator(isch) using a range, i.e.:

```rust
    let mut nonce = {
        let mut seed = (0..).step_by(3);
        move || seed.next().unwrap()
    };
```

Whenver we call `nonce()`, we get a unique value back from the sequence `0, 3, 6 ..`, to mimick `nonce1` and `nonce2`.

With this, we could replace

```rust
    // resolve a "random" domain name to prevent caching
    static mut NONCE: usize = 0;

    let (nonce1, nonce2) = unsafe {
        let i = NONCE;
        NONCE += 2;
        (i, i + 1)
    };

    let rpc_client = rpc.clone();
    let handle = tokio::spawn(async move {
        let _ = rpc_client
            .resolve_hostname(format!("test{nonce1}.mullvad.net"))
            .await;

        // Retry just to be sure. DNS config change may not take effect immediately.
        tokio::time::sleep(Duration::from_secs(2)).await;
        let _ = rpc_client
            .resolve_hostname(format!("test{nonce2}.mullvad.net"))
            .await;
    });

```

with

```rust
    // resolve a "random" domain name to prevent caching
    let mut nonce = {
        let mut nums = (0..).step_by(3);
        move || nums.next().unwrap()
    };

    let rpc_client = rpc.clone();
    tokio::spawn(async move {
        // Retry multiple times just to be sure. DNS config change may not take effect immediately.
        for _ in 1..=2 {
            let _ = rpc_client
                .resolve_hostname(format!("test{}.mullvad.net", nonce()))
                .await;
            tokio::time::sleep(Duration::from_secs(2)).await;
        }
    });

```

What do you think? :blush:

To be perfectly honest, one could get away with using the loop-variable as a seed for the nonce :sweat_smile:
</blockquote></details>

I think the static variable is necessary since these names should be unique across calls to `run_dns_config_test`. I think your suggestion will reset the counter to 0 every time.

But you gave me the idea to use an atomic type, which I think looks nearly as clean. Thoughts?

The other suggestion (loop + closure) is nicer than what I did indeed!
___
*[`test-rpc/src/client.rs` line 145 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/105#-NchH--W37NT8XUE4GFD:-NchSYzP-PmkLbB1EwUW:b4pvox9) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/9a7e4da4fc2d43b2952db89b82dc77f12f38d9f4/test-rpc/src/client.rs#L145)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Using a regular `for`-loop leads to less stateful code (i.e. less to track in your head while reading the code):

```rust
    async fn mullvad_daemon_wait_for_state(
        self,
        accept_state_fn: impl Fn(ServiceStatus) -> bool,,
    ) -> Result<(), test_rpc::Error> {
        const MAX_ATTEMPTS: usize = 10;
        const POLL_INTERVAL: Duration = Duration::from_secs(3);
        for _ in 0..MAX_ATTEMPTS {
            let last_state = self.mullvad_daemon_get_status().await?;
            // A regular `if` would also work, `match` was just shorter 
            match accept_state_fn(last_state) {
                true => return Ok(()),
                false => tokio::time::sleep(POLL_INTERVAL).await,
            }
        }
        Err(Error::Timeout)
    }
```

Also, would there be any point in returning the accepted state? Worst case the caller just has to drop it :shrug:
</blockquote></details>

Agree with this. The only drawback with this is that the code sleeps needlessly after the last attempt, which is probably why I didn't use a for loop initially. But maybe the simpler code is worth that cost. :)


<!-- Sent from Reviewable.io -->

2023-08-28 07:23 UTC, MarkusPettersson98 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/105#-:-Ncv0YJd5FTquiJ1biXI:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`test-manager/src/tests/dns.rs` line 590 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/105#-NchAVGEEmtaOvaguGqA:-Ncuxp2M0tGnYUc6J67v:bv6kgfn) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/cf7e0c37dd4d4716b38c813292c1d2e9401abdd4/test-manager/src/tests/dns.rs#L590)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I think the static variable is necessary since these names should be unique across calls to `run_dns_config_test`. I think your suggestion will reset the counter to 0 every time.

But you gave me the idea to use an atomic type, which I think looks nearly as clean. Thoughts?

The other suggestion (loop + closure) is nicer than what I did indeed!
</blockquote></details>

Alright, then I understand the need for `static` :) I think the atomic variable-solution looks clean & clear, ship it! :shipit: 
___
*[`test-rpc/src/client.rs` line 145 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/105#-NchH--W37NT8XUE4GFD:-NcuyVGx-5IzDtWpN41V:bjfae0w) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/9a7e4da4fc2d43b2952db89b82dc77f12f38d9f4/test-rpc/src/client.rs#L145)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Agree with this. The only drawback with this is that the code sleeps needlessly after the last attempt, which is probably why I didn't use a for loop initially. But maybe the simpler code is worth that cost. :)
</blockquote></details>

I think so, but it could maybe lead to frustration for future us :shrug:

One could branch on the loop-variable (which is not even considered atm) to decide if we should sleep or just continue

```rust
        for attempt in 1..=MAX_ATTEMPTS {
            let last_state = self.mullvad_daemon_get_status().await?;
            match accept_state_fn(last_state) {
                true => return Ok(last_state),
                false => {
                    if attempt != MAX_ATTEMPTS {
                        tokio::time::sleep(POLL_INTERVAL).await
                    } else {
                        continue;
                    }
                }
            }
        }
        Err(Error::Timeout)
```
With proper formatting (`false => ..` branch not condensed to one line) this solution tend to look quite long-winded, so syntactically I don't think skipping the sleep on the last iteration carries its weight. I'll leave that up to you :blush: 


<!-- Sent from Reviewable.io -->

2023-08-28 14:15 UTC, dlon reviewed
> Dismissed @MarkusPettersson98 from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/105)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @dlon)

___
*[`test-manager/src/tests/dns.rs` line 590 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/105#-NchAVGEEmtaOvaguGqA:-NcwUmAACXycjY1EraQX:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/cf7e0c37dd4d4716b38c813292c1d2e9401abdd4/test-manager/src/tests/dns.rs#L590)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Alright, then I understand the need for `static` :) I think the atomic variable-solution looks clean & clear, ship it! :shipit:
</blockquote></details>

Done.
___
*[`test-rpc/src/client.rs` line 145 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/105#-NchH--W37NT8XUE4GFD:-NcwUrA602oAN38uW9T_:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/9a7e4da4fc2d43b2952db89b82dc77f12f38d9f4/test-rpc/src/client.rs#L145)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

I think so, but it could maybe lead to frustration for future us :shrug:

One could branch on the loop-variable (which is not even considered atm) to decide if we should sleep or just continue

```rust
        for attempt in 1..=MAX_ATTEMPTS {
            let last_state = self.mullvad_daemon_get_status().await?;
            match accept_state_fn(last_state) {
                true => return Ok(last_state),
                false => {
                    if attempt != MAX_ATTEMPTS {
                        tokio::time::sleep(POLL_INTERVAL).await
                    } else {
                        continue;
                    }
                }
            }
        }
        Err(Error::Timeout)
```
With proper formatting (`false => ..` branch not condensed to one line) this solution tend to look quite long-winded, so syntactically I don't think skipping the sleep on the last iteration carries its weight. I'll leave that up to you :blush:
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-28 14:15 UTC, merged