Add DNS leak tests
mullvad/mullvadvpn-app-tests pull request #55
Opened 2023-03-13 17:33 UTC by dlon

These tests ensure that there are no DNS leaks, both inside and outside of the tunnel, when for the default resolver, custom DNS with a private IP, and custom DNS with a public IP. They also make sure that outbound traffic *is* observed when allowed.

2023-03-14 14:15 UTC, Jontified requested changes

2023-03-14 14:23 UTC, dlon commented on scripts/setup-network.sh
> +ip link set up dev wg-relay0
It should probably be destroyed in `destroy-network.sh`. It should also be destroyed automagically when the network namespace is destroyed.

2023-03-14 14:59 UTC, dlon commented on scripts/setup-network.sh
> +trap "rm $temp_wg_conf" EXIT TERM
Good catch! Fixed.

2023-03-14 15:00 UTC, dlon commented on scripts/setup-network.sh
> +ip link set up dev wg-relay0
I've added it to the cleanup script.

2023-03-14 15:00 UTC, dlon commented on test-manager/src/tests/dns.rs
> +            base64::decode("mPue6Xt0pdz4NRAhfQSp/SLKo7kV7DW+2zvBq0N9iUI=").unwrap(),
Fixed.

2023-03-14 15:08 UTC, dlon commented on test-manager/src/tests/dns.rs
> +/// The test succeeds if and only if all expected outbound packets on port 53 are observed.
I've clarified this.

2023-03-14 15:32 UTC, Jontified requested changes

2023-03-14 15:32 UTC, Jontified commented on test-manager/src/tests/dns.rs
> +            non_tunnel_result.packets.len() >= 2,
Nit: why not have `==`?

2023-03-14 15:32 UTC, Jontified commented on test-manager/src/tests/dns.rs
> +const TUN_REMOTE_ADDR: Ipv4Addr = Ipv4Addr::new(192, 168, 15, 1);
Perhaps we should reference that this is set in the `setup_network.sh` script?

2023-03-14 15:32 UTC, Jontified commented on test-manager/src/tests/dns.rs
> +    let result = monitor.wait().await.unwrap();
nit: `monitor_results`?

2023-03-14 15:41 UTC, Jontified approved these changes

2023-03-14 15:46 UTC, dlon commented on test-manager/src/tests/dns.rs
> +            non_tunnel_result.packets.len() >= 2,
Answered previously.

2023-03-14 18:52 UTC, dlon commented on test-manager/src/tests/dns.rs
> +/// Test whether the expected default DNS resolver is used by `gethostbyaddr` (via `ToSocketAddrs`).
Should say: `getaddrinfo`

2023-03-15 14:18 UTC, Jontified approved these changes

2023-03-15 14:45 UTC, merged