Rotate wg key test des 51
mullvad/mullvadvpn-app-tests pull request #68
Opened 2023-03-30 08:52 UTC by Jontified

Create a test which makes sure that the daemon automatically rotates the WG key when it becomes outdated.

2023-03-30 11:31 UTC, dlon requested changes
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68)* status: all files reviewed, 13 unresolved discussions (waiting on @Jontified)

___
*[`test-manager/src/tests/account.rs` line 261 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NRm0oUM2Xxxy1s37ybH:-NRm0oUM2Xxxy1s37ybI:b7g7lkv) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/292c51e308b02360df8d58c3429dec9f8cc6670b/test-manager/src/tests/account.rs#L261)):*
> ```XML
>         .pubkey;
>     // Stop daemon
>     rpc.toggle_daemon_service(false)
> ```

For consistency, I think the RPC should be named `mullvad_daemon_set_state`.
___
*[`test-manager/src/tests/account.rs` line 273 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NRm1IGe2VhRfu1WMwM7:-NRm1IGe2VhRfu1WMwM8:bvyx1jm) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/292c51e308b02360df8d58c3429dec9f8cc6670b/test-manager/src/tests/account.rs#L273)):*
> ```XML
>     const KEY_ROTATION_WAIT_SECONDS: u64 = 70;
>     log::info!("Sleeping for {} seconds to wait for key rotation to happen", KEY_ROTATION_WAIT_SECONDS);
>     tokio::time::sleep(std::time::Duration::from_secs(KEY_ROTATION_WAIT_SECONDS)).await;
> ```

Instead of sleeping, I think it would be cleaner to wait for the tunnel event here, and time out after a couple of minutes.
___
*[`test-rpc/src/client.rs` line 171 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NRm3WMuDuplYbKI2J0_:-NRm3WMuDuplYbKI2J0a:bl5f7z4) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/292c51e308b02360df8d58c3429dec9f8cc6670b/test-rpc/src/client.rs#L171)):*
> ```XML
>     }
> 
>     pub async fn set_daemon_log_level(&self, verbosity_level: usize) -> Result<(), Error> {
> ```

Could we use an enum for the verbosity level? It would be clearer what the level meant, and you wouldn't be able to set a nonsensical level.
___
*[`test-rpc/src/client.rs` line 192 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NRm2qG3EWVKtzCZQ9YU:-NRm2qG3EWVKtzCZQ9YV:buzlgdt) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/292c51e308b02360df8d58c3429dec9f8cc6670b/test-rpc/src/client.rs#L192)):*
> ```XML
>     }
> 
>     pub async fn toggle_daemon_service(&mut self, on: bool) -> Result<(), Error> {
> ```

The reference doesn't have to be mutable.
___
*[`test-rpc/src/client.rs` line 196 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NRm2slI3WJ-vlbgh4PJ:-NRm2slI3WJ-vlbgh4PK:buzlgdt) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/292c51e308b02360df8d58c3429dec9f8cc6670b/test-rpc/src/client.rs#L196)):*
> ```XML
>     }
> 
>     pub async fn make_device_json_old(&mut self) -> Result<(), Error> {
> ```

The reference doesn't have to be mutable.
___
*[`test-runner/Cargo.toml` line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NRmECC94-TV81u2uqk8:-NRmECC94-TV81u2uqk9:btuau5n) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/292c51e308b02360df8d58c3429dec9f8cc6670b/test-runner/Cargo.toml#L22)):*
> ```TOML
> 
> mullvad-management-interface = { git = "https://github.com/mullvad/mullvadvpn-app", branch = "main" }
> mullvad-types = { git = "https://github.com/mullvad/mullvadvpn-app", branch = "main" }
> ```

Do we not need to update `ci-runtests.sh` to set the correct rev?
___
*[`test-runner/src/app.rs` line 122 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NRmGGPg4AWE-il7B64f:-NRmGGPg4AWE-il7B64g:b-38zsf5) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/292c51e308b02360df8d58c3429dec9f8cc6670b/test-runner/src/app.rs#L122)):*
> ```XML
> pub async fn make_device_json_old() -> Result<(), Error> {
>     log::error!("device json call");
>     const DEVICE_JSON_PATH: &str = "/etc/mullvad-vpn/device.json";
> ```

This is OS-dependent.
___
*[`test-runner/src/app.rs` line 124 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NRmEnHbCj23PS260gYq:-NRmEnHbCj23PS260gYr:b-ibzwrd) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/292c51e308b02360df8d58c3429dec9f8cc6670b/test-runner/src/app.rs#L124)):*
> ```XML
>     const DEVICE_JSON_PATH: &str = "/etc/mullvad-vpn/device.json";
>     let device_json = tokio::fs::read_to_string(DEVICE_JSON_PATH).await.map_err(|e| Error::FileSystem(e.to_string()))?;
>     log::error!("{device_json:?}");
> ```

Not an error.
___
*[`test-runner/src/app.rs` line 125 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NRmEr0R7vXzTM-hgEJJ:-NRmEr0R7vXzTM-hgEJK:b-d3l9) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/292c51e308b02360df8d58c3429dec9f8cc6670b/test-runner/src/app.rs#L125)):*
> ```XML
>     let device_json = tokio::fs::read_to_string(DEVICE_JSON_PATH).await.map_err(|e| Error::FileSystem(e.to_string()))?;
>     log::error!("{device_json:?}");
>     let mut device_state: PrivateDeviceState = serde_json::from_str(&device_json).map_err(|e| Error::FileSerialization(e.to_string()))?;
> ```

Could we not replace the `created` field without deserializing anything? Something like

```rust
let created = config
        .get_mut("logged_in").unwrap()
        .get_mut("device").unwrap()
        .get_mut("created").unwrap();
*created = ...;
```
___
*[`test-runner/src/app.rs` line 138 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NRmEkvJ47MAgvM8FlTl:-NRmEkvJ47MAgvM8FlTm:b-ibzwrd) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/292c51e308b02360df8d58c3429dec9f8cc6670b/test-runner/src/app.rs#L138)):*
> ```XML
>     }
>     let device_json = serde_json::to_string(&device_state).map_err(|e| Error::FileSerialization(e.to_string()))?;
>     log::error!("{device_json:?}");
> ```

Not an error.
___
*[`test-runner/src/app.rs` line 142 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NRmEoYtC-qQVlW0cIHw:-NRmEoYtC-qQVlW0cIHx:b-ibzwrd) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/292c51e308b02360df8d58c3429dec9f8cc6670b/test-runner/src/app.rs#L142)):*
> ```XML
> 
>     let device_json = tokio::fs::read_to_string(DEVICE_JSON_PATH).await.map_err(|e| Error::FileSystem(e.to_string()))?;
>     log::error!("New device_json: {device_json:?}");
> ```

Not an error.
___
*[`test-runner/src/sys.rs` line 144 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NRmG_8vDbLuCHP3DCgz:-NRmG_8vDbLuCHP3DCh-:b-lgcbgx) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/292c51e308b02360df8d58c3429dec9f8cc6670b/test-runner/src/sys.rs#L144)):*
> ```XML
> }
> 
> #[cfg(target_os = "linux")]
> ```

Missing implementations for non-Linux.
___
*[`test-runner/src/sys.rs` line 191 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NRmGcMf01dwufsYEb3Z:-NRmGcMf01dwufsYEb3_:b-lgcbgx) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/292c51e308b02360df8d58c3429dec9f8cc6670b/test-runner/src/sys.rs#L191)):*
> ```XML
> }
> 
> #[cfg(target_os = "linux")]
> ```

Missing implementations for non-Linux.


<!-- Sent from Reviewable.io -->

2023-05-02 11:18 UTC, dlon requested changes
> Reviewed 23 of 23 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68)* status: all files reviewed, 21 unresolved discussions (waiting on @Jontified)

___
*[`test-manager/src/logging.rs` line 95 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NUR9pLcDWuzI-_d_3Vl:-NUR9pLcDWuzI-_d_3Vm:bkeho1h) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/d6c4b8531028c405739b9ea7d512e4917c43b43d/test-manager/src/logging.rs#L95)):*
> ```XML
> ) -> Result<TestOutput, Error>
> where
>     F: Fn(super::tests::TestContext, ServiceClient, MullvadClient) -> R,
> ```

It seems redundant to pass in the mullvad client here now that it can be constructed using the context. But we don't have to change this now.
___
*[`test-manager/src/run_tests.rs` line 112 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NURA76UD5OIrl-ABuD2:-NURA76UD5OIrl-ABuD3:b-dcvood) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/d6c4b8531028c405739b9ea7d512e4917c43b43d/test-manager/src/run_tests.rs#L112)):*
> ```XML
>     println!("TESTS THAT SUCCEEDED:");
>     for test in successful_tests {
>         println!("{test}");
> ```

Should we not use the `log` macros rather than `println`?
___
*[`test-manager/src/tests/account.rs` line 295 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NUR5SZr3IPmYyZW0sb8:-NUR5SZr3IPmYyZW0sb9:bm6gauj) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/d6c4b8531028c405739b9ea7d512e4917c43b43d/test-manager/src/tests/account.rs#L295)):*
> ```XML
>     drop(mullvad_client);
>     // Give the connection some time to drop
>     std::thread::sleep(Duration::from_secs(1));
> ```

Could we move this into `new_client` (and `old_client`) as well as remove the sleep from `RpcClientProvider::as_type`? Also, use the async sleep.
___
*[`test-rpc/src/mullvad_daemon.rs` line 26 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NUR7A8aB9j2Buoc81Ik:-NUR7A8aB9j2Buoc81Il:b-4o42og) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/d6c4b8531028c405739b9ea7d512e4917c43b43d/test-rpc/src/mullvad_daemon.rs#L26)):*
> ```XML
> pub enum Verbosity {
>     None,
>     V,
> ```

How about `Disabled | Verbose | Debug | Info`?
___
*[`test-runner/src/sys.rs` line 165 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NUR88ST9YGD1d-X0nhX:-NUR88ST9YGD1d-X0nhY:b-f2kctj) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/d6c4b8531028c405739b9ea7d512e4917c43b43d/test-runner/src/sys.rs#L165)):*
> ```XML
>     };
>     // TODO: This should perhaps read in the current file and rewrite the verbosity
>     let systemd_service_file_content = format!(
> ```

You could perhaps use an override config here instead, and only change the part we care about.
___
*[`test-runner/src/sys.rs` line 188 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NUR9W_x7r89oTK8sGNv:-NUR9W_x7r89oTK8sGNw:brd9l1h) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/d6c4b8531028c405739b9ea7d512e4917c43b43d/test-runner/src/sys.rs#L188)):*
> ```XML
>     );
> 
>     std::fs::write(SYSTEMD_SERVICE_FILE, systemd_service_file_content)
> ```

`tokio::fs::write`.
___
*[`test-runner/src/sys.rs` line 191 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NUR8dyO-3_xc_02Nx8Z:-NUR8dyO-3_xc_02Nx8_:buc0c9q) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/d6c4b8531028c405739b9ea7d512e4917c43b43d/test-runner/src/sys.rs#L191)):*
> ```XML
>         .map_err(|e| test_rpc::Error::FileSystem(e.to_string()))?;
> 
>     std::process::Command::new("systemctl")
> ```

Use `tokio::process::Command`.
___
*[`test-runner/src/sys.rs` line 195 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NUR9Zgr0pDAxKIQbZA6:-NUR9Zgr0pDAxKIQbZA7:buc0c9q) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/d6c4b8531028c405739b9ea7d512e4917c43b43d/test-runner/src/sys.rs#L195)):*
> ```XML
>         .spawn()
>         .map_err(|e| test_rpc::Error::Service(e.to_string()))?;
>     std::process::Command::new("systemctl")
> ```

Use `tokio::process::Command`.
___
*[`test-runner/src/sys.rs` line 200 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NUR8_kA0VctxQEnwgcB:-NUR8_kA0VctxQEnwgcC:b8wefic) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/d6c4b8531028c405739b9ea7d512e4917c43b43d/test-runner/src/sys.rs#L200)):*
> ```XML
>         .map_err(|e| test_rpc::Error::Service(e.to_string()))?;
> 
>     std::thread::sleep(std::time::Duration::from_millis(1000));
> ```

Use `tokio::time::sleep`.
___
*[`test-runner/src/sys.rs` line 231 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NUR91fNDI0WiGC-Ymx3:-NUR91fNDI0WiGC-Ymx4:b8wefic) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/d6c4b8531028c405739b9ea7d512e4917c43b43d/test-runner/src/sys.rs#L231)):*
> ```XML
>         .map_err(|e| test_rpc::Error::Service(e.to_string()))?;
>     // NOTE: Need to sleep to let the service shut down
>     std::thread::sleep(std::time::Duration::from_millis(1000));
> ```

Use `tokio::time::sleep`.
___
*[`test-runner/src/sys.rs` line 276 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NUR8rZE8HjrOKj6mM2k:-NUR8rZE8HjrOKj6mM2l:buc0c9q) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/d6c4b8531028c405739b9ea7d512e4917c43b43d/test-runner/src/sys.rs#L276)):*
> ```XML
> pub fn set_mullvad_daemon_service_state(on: bool) -> Result<(), test_rpc::Error> {
>     if on {
>         std::process::Command::new("systemctl")
> ```

Use `tokio::process::Command`.
___
*[`test-runner/src/sys.rs` line 282 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NUR9G5R29QomlvcYf5G:-NUR9G5R29QomlvcYf5H:buc0c9q) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/d6c4b8531028c405739b9ea7d512e4917c43b43d/test-runner/src/sys.rs#L282)):*
> ```XML
>         std::thread::sleep(std::time::Duration::from_millis(1000));
>     } else {
>         std::process::Command::new("systemctl")
> ```

Use `tokio::process::Command`.
___
*[`test-runner/src/sys.rs` line 286 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NUR8s7b4NA12sXlikQW:-NUR8s7b4NA12sXlikQX:b8wefic) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/d6c4b8531028c405739b9ea7d512e4917c43b43d/test-runner/src/sys.rs#L286)):*
> ```XML
>             .spawn()
>             .map_err(|e| test_rpc::Error::Service(e.to_string()))?;
>         std::thread::sleep(std::time::Duration::from_millis(1000));
> ```

Use `tokio::time::sleep`.
___
*[`test-runner/src/sys.rs` line 294 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NUR98z50N2-ZeRqHPnl:-NUR98z50N2-ZeRqHPnm:buc0c9q) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/d6c4b8531028c405739b9ea7d512e4917c43b43d/test-runner/src/sys.rs#L294)):*
> ```XML
> pub fn set_mullvad_daemon_service_state(on: bool) -> Result<(), test_rpc::Error> {
>     if on {
>         std::process::Command::new("net")
> ```

Use `tokio::process::Command`.
___
*[`test-runner/src/sys.rs` line 298 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NUR981wCYSzqPHiREm0:-NUR981wCYSzqPHiREm1:b8wefic) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/d6c4b8531028c405739b9ea7d512e4917c43b43d/test-runner/src/sys.rs#L298)):*
> ```XML
>             .spawn()
>             .map_err(|e| test_rpc::Error::Service(e.to_string()))?;
>         std::thread::sleep(std::time::Duration::from_millis(1000));
> ```

Use `tokio::time::sleep`.
___
*[`test-runner/src/sys.rs` line 300 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NUR9AU4D-CPWSCdrJuv:-NUR9AU4D-CPWSCdrJuw:buc0c9q) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/d6c4b8531028c405739b9ea7d512e4917c43b43d/test-runner/src/sys.rs#L300)):*
> [...]

2023-05-02 11:23 UTC, dlon requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68)* status: all files reviewed, 21 unresolved discussions (waiting on @Jontified)

___
*[`test-runner/src/sys.rs` line 231 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NUR91fNDI0WiGC-Ymx3:-NURBm2iA3WlpxXSZZ_C:b-iksuxs) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/d6c4b8531028c405739b9ea7d512e4917c43b43d/test-runner/src/sys.rs#L231)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Use `tokio::time::sleep`.
</blockquote></details>

Also, maybe the above works fine in practice, but it would be more reliable to query the status of the service until it's no longer running.


<!-- Sent from Reviewable.io -->

2023-05-03 20:32 UTC, Jontified reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68)* status: 13 of 23 files reviewed, 16 unresolved discussions (waiting on @dlon)

___
*[`test-manager/src/run_tests.rs` line 112 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NURA76UD5OIrl-ABuD2:-NURFXGcEr5DyjWsPgAV:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/d6c4b8531028c405739b9ea7d512e4917c43b43d/test-manager/src/run_tests.rs#L112)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Should we not use the `log` macros rather than `println`?
</blockquote></details>

Done.
___
*[`test-manager/src/tests/account.rs` line 261 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NRm0oUM2Xxxy1s37ybH:-NUQhAXB-C2Y0AaK6WpN:b-6y497o) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/292c51e308b02360df8d58c3429dec9f8cc6670b/test-manager/src/tests/account.rs#L261)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

For consistency, I think the RPC should be named `mullvad_daemon_set_state`.
</blockquote></details>

I've changed this to`set_mullvad_daemon_service_state` to make it as clear as possible.
___
*[`test-manager/src/tests/account.rs` line 273 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NRm1IGe2VhRfu1WMwM7:-NUQhIYx0WcWc9rD8fS1:bt2vr1b) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/292c51e308b02360df8d58c3429dec9f8cc6670b/test-manager/src/tests/account.rs#L273)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Instead of sleeping, I think it would be cleaner to wait for the tunnel event here, and time out after a couple of minutes.
</blockquote></details>

Fixed.
___
*[`test-manager/src/tests/account.rs` line 295 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NUR5SZr3IPmYyZW0sb8:-NUY86YV6m91X-XNtNhC:b1q5rvj) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/d6c4b8531028c405739b9ea7d512e4917c43b43d/test-manager/src/tests/account.rs#L295)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Could we move this into `new_client` (and `old_client`) as well as remove the sleep from `RpcClientProvider::as_type`? Also, use the async sleep.
</blockquote></details>

Hmm, does that make sense? We are not sleeping here because we're creating a new client, we're sleeping because we need some time to drop the old one.
___
*[`test-rpc/src/client.rs` line 171 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NRm3WMuDuplYbKI2J0_:-NUQhJUm26l1Vz53rz8W:bt2vr1b) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/292c51e308b02360df8d58c3429dec9f8cc6670b/test-rpc/src/client.rs#L171)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Could we use an enum for the verbosity level? It would be clearer what the level meant, and you wouldn't be able to set a nonsensical level.
</blockquote></details>

Fixed.
___
*[`test-rpc/src/client.rs` line 192 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NRm2qG3EWVKtzCZQ9YU:-NUQmybGDCFmzConvu1c:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/292c51e308b02360df8d58c3429dec9f8cc6670b/test-rpc/src/client.rs#L192)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

The reference doesn't have to be mutable.
</blockquote></details>

Done.
___
*[`test-rpc/src/client.rs` line 196 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NRm2slI3WJ-vlbgh4PJ:-NUQmzDn88gR2Yz3Qt1i:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/292c51e308b02360df8d58c3429dec9f8cc6670b/test-rpc/src/client.rs#L196)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

The reference doesn't have to be mutable.
</blockquote></details>

Done.
___
*[`test-rpc/src/mullvad_daemon.rs` line 26 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NUR7A8aB9j2Buoc81Ik:-NUSVXSd49l2Q5_FguXt:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/d6c4b8531028c405739b9ea7d512e4917c43b43d/test-rpc/src/mullvad_daemon.rs#L26)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

How about `Disabled | Verbose | Debug | Info`?
</blockquote></details>

Done.
___
*[`test-runner/Cargo.toml` line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NRmECC94-TV81u2uqk8:-NUR9N9C-TPKdo0-WpbH:by79ius) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/292c51e308b02360df8d58c3429dec9f8cc6670b/test-runner/Cargo.toml#L22)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Do we not need to update `ci-runtests.sh` to set the correct rev?
</blockquote></details>

This turned out not to be important, I removed it.
___
*[`test-runner/src/app.rs` line 122 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NRmGGPg4AWE-il7B64f:-NUQnEPK7qdD2P-mS9OK:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/292c51e308b02360df8d58c3429dec9f8cc6670b/test-runner/src/app.rs#L122)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This is OS-dependent.
</blockquote></details>

Done.
___
*[`test-runner/src/app.rs` line 124 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NRmEnHbCj23PS260gYq:-NUQnF9Y19xC01-p9s8X:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/292c51e308b02360df8d58c3429dec9f8cc6670b/test-runner/src/app.rs#L124)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Not an error.
</blockquote></details>

Done.
___
*[`test-runner/src/app.rs` line 138 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NRmEkvJ47MAgvM8FlTl:-NUQnnpFAqrpKkJ5fZzv:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/292c51e308b02360df8d58c3429dec9f8cc6670b/test-runner/src/app.rs#L138)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Not an error.
</blockquote></details>

Done.
___
*[`test-runner/src/app.rs` line 142 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NRmEoYtC-qQVlW0cIHw:-NUQnoOf53yMLGwE_cCc:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/292c51e308b02360df8d58c3429dec9f8cc6670b/test-runner/src/app.rs#L142)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Not an error.
</blockquote></details>

Done.
___
*[`test-runner/src/sys.rs` line 144 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NRmG_8vDbLuCHP3DCgz:-NUQnpoLCYZvXyyUTDkB:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/292c51e308b02360df8d58c3429dec9f8cc6670b/test-runner/src/sys.rs#L144)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Missing implementations for non-Linux.
</blockquote></details>

Done.
___
*[`test-runner/src/sys.rs` line 191 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NRmGcMf01dwufsYEb3Z:-NUQnqHp6xuIseNK-z_z:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/292c51e308b02360df8d58c3429dec9f8cc6670b/test-runner/src/sys.rs#L191)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Missing implementations for non-Linux.
</blockquote></details>

Done.
___
*[`test-runner/src/sys.rs` line 188 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NUR9W_x7r89oTK8sGNv:-NUREul2Ah0lGQnT5LxU:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/d6c4b8531028c405739b9ea7d512e4917c43b43d/test-runner/src/sys.rs#L188 [...]

2023-05-04 08:17 UTC, dlon requested changes
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68)* status: all files reviewed, 4 unresolved discussions (waiting on @Jontified)

___
*[`test-manager/src/tests/account.rs` line 295 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NUR5SZr3IPmYyZW0sb8:-NU_lMdq7eOH0iJ0Lh0v:b7854wn) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/d6c4b8531028c405739b9ea7d512e4917c43b43d/test-manager/src/tests/account.rs#L295)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

Hmm, does that make sense? We are not sleeping here because we're creating a new client, we're sleeping because we need some time to drop the old one.
</blockquote></details>

You're right about that. That is why we sleep there at the moment, though, so we wouldn't have to add this sleep hack in two places. Since it's a hack, I still favor that workaround.

We should probably solve it properly (figure out why the unix socket isn't properly reset whenever a client is dropped) and remove the sleeps, but that's pretty out of scope here.
___
*[`test-runner/src/app.rs` line 114 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NU_nDd-Cxc9xgrMqzad:-NU_nDd-Cxc9xgrMqzae:b-me89rk) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/d6c4b8531028c405739b9ea7d512e4917c43b43d/test-runner/src/app.rs#L114)):*
> ```XML
> #[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
> #[serde(rename_all = "snake_case")]
> enum PrivateDeviceState {
> ```

We could probably remove all of these types here now, I think.
___
*[`test-runner/src/sys.rs` line 231 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NUR91fNDI0WiGC-Ymx3:-NU_oCpU6ekza9lrL4O9:b4n2duc) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/d6c4b8531028c405739b9ea7d512e4917c43b43d/test-runner/src/sys.rs#L231)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Could we leave a TODO note or create a card about polling the status? I guess we could also use the `net` wrapper to do this.
___
*[`test-runner/src/sys.rs` line 304 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NUR98XPDj5RgNEIOVXf:-NU_orfZ0O3qch0bN9l4:b-3hwq32) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/d6c4b8531028c405739b9ea7d512e4917c43b43d/test-runner/src/sys.rs#L304)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Are you sure the sleeps are needed in this func? `net` is supposed to block until the status has changed (or failure).
___
*[`test-runner/src/sys.rs` line 191 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NU_nuL5C7ygdR_D-VM8:-NU_nuL5C7ygdR_D-VM9:bxevz8) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/7de6f3971c65c7ac747892956a1c981b567d35d4/test-runner/src/sys.rs#L191)):*
> ```XML
>     tokio::process::Command::new("systemctl")
>         .args(["daemon-reload"])
>         .spawn()
> ```

Nit: Here and elsewhere, you should be able to use `cmd.status()` or `cmd.output()` directly.
___
*[`test-runner/src/sys.rs` line 214 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NU_pSqc0kIykpuoiPrA:-NU_pSqc0kIykpuoiPrB:bboyqdc) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/7de6f3971c65c7ac747892956a1c981b567d35d4/test-runner/src/sys.rs#L214)):*
> ```XML
>     let verbosity = match verbosity_level {
>         Verbosity::None => "",
>         Verbosity::V => "-v",
> ```

Using wrong variants here.


<!-- Sent from Reviewable.io -->

2023-05-04 09:27 UTC, Jontified reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`test-manager/src/tests/account.rs` line 295 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NUR5SZr3IPmYyZW0sb8:-NU_t8y1Ew5gqfp6HhhD:b-9aiw7j) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/d6c4b8531028c405739b9ea7d512e4917c43b43d/test-manager/src/tests/account.rs#L295)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

You're right about that. That is why we sleep there at the moment, though, so we wouldn't have to add this sleep hack in two places. Since it's a hack, I still favor that workaround.

We should probably solve it properly (figure out why the unix socket isn't properly reset whenever a client is dropped) and remove the sleeps, but that's pretty out of scope here.
</blockquote></details>

Fair enough, done.
___
*[`test-runner/src/app.rs` line 114 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NU_nDd-Cxc9xgrMqzad:-NU_tL93D-ICkGQq-SVG:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/d6c4b8531028c405739b9ea7d512e4917c43b43d/test-runner/src/app.rs#L114)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

We could probably remove all of these types here now, I think.
</blockquote></details>

Done.
___
*[`test-runner/src/sys.rs` line 231 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NUR91fNDI0WiGC-Ymx3:-NU_xkpD0Fm76wTlMCKq:b-hc86l9) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/d6c4b8531028c405739b9ea7d512e4917c43b43d/test-runner/src/sys.rs#L231)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Could we leave a TODO note or create a card about polling the status? I guess we could also use the `net` wrapper to do this.
</blockquote></details>

I'm sorry, I actually fixed this for Linux but I forgot to fix it for windows. I've add a `net` call to stop afterwards. This causes a double-stop but should guarantee that the service is stopped.
___
*[`test-runner/src/sys.rs` line 304 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NUR98XPDj5RgNEIOVXf:-NU_y6fe-mEybPnC388x:b1bp1rr) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/d6c4b8531028c405739b9ea7d512e4917c43b43d/test-runner/src/sys.rs#L304)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Are you sure the sleeps are needed in this func? `net` is supposed to block until the status has changed (or failure).
</blockquote></details>

I've tried it out, and it seems to work fine to remove the sleep.
___
*[`test-runner/src/sys.rs` line 191 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NU_nuL5C7ygdR_D-VM8:-NU_yCZCAQkfrKThnYKt:bt2vr1b) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/7de6f3971c65c7ac747892956a1c981b567d35d4/test-runner/src/sys.rs#L191)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nit: Here and elsewhere, you should be able to use `cmd.status()` or `cmd.output()` directly.
</blockquote></details>

Fixed.
___
*[`test-runner/src/sys.rs` line 214 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68#-NU_pSqc0kIykpuoiPrA:-NU_u2Xv7bYiMJx8BKoJ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/7de6f3971c65c7ac747892956a1c981b567d35d4/test-runner/src/sys.rs#L214)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Using wrong variants here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-04 11:09 UTC, dlon approved these changes
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/68)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Jontified)



<!-- Sent from Reviewable.io -->

2023-05-04 12:16 UTC, merged