Update vms before running tests (if possible)
mullvad/mullvadvpn-app-tests pull request #85
Opened 2023-07-05 11:53 UTC by MarkusPettersson98

In VM images where there are known package managers (e.g. `apt` in Ubuntu/Debian, `dnf` in Fedora) we could allow for automatically updating system packages before proceeding with running tests.

2023-07-06 09:47 UTC, dlon requested changes
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/85)* status: all files reviewed, 3 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`test-manager/src/vm/ssh.rs` line 18 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/85#-NZe_EwB8k32rGZEgGnn:-NZe_EwB8k32rGZEgGno:b-nuw9xq) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/2d81a53fa4b2382b978610a6f72c62a53356ceec/test-manager/src/vm/ssh.rs#L18)):*
> ```XML
>         log::info!("initializing a new SSH session ..");
>         // Set up the SSH connection
>         let stream = TcpStream::connect(SocketAddr::new(ip, SSHSession::port()))
> ```

Calling a sync `connect` here is not ideal. It will block the entire tokio runtime. Probably fine in practice, but I think we should at least spawn a blocking thread.
___
*[`test-manager/src/vm/ssh.rs` line 36 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/85#-NZe_VrlC2OGb2AWs2lu:-NZe_VrlC2OGb2AWs2lv:b-e23hua) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/2d81a53fa4b2382b978610a6f72c62a53356ceec/test-manager/src/vm/ssh.rs#L36)):*
> ```XML
> 
>     /// Execute an arbitrary string of commands via ssh.
>     pub async fn exec(&self, command: &str) -> Result<String> {
> ```

This function isn't asynchronous. It would probably make sense to spawn a blocking task here or at the call site.
___
*[`test-manager/src/vm/update.rs` line 13 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/85#-NZe_hzj7DQsT-U4Bjcp:-NZe_hzj7DQsT-U4Bjcq:b-n1zswr) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/2d81a53fa4b2382b978610a6f72c62a53356ceec/test-manager/src/vm/update.rs#L13)):*
> ```XML
> 
> pub async fn packages(config: &VmConfig, instance: &dyn super::VmInstance) -> Result<Update> {
>     if let Provisioner::Noop = config.provisioner {
> ```

Nit: `config.provisioner == Provisioner::Noop` should work as `Provisioner` implements `PartialEq`.


<!-- Sent from Reviewable.io -->

2023-07-06 15:06 UTC, MarkusPettersson98 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/85)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`test-manager/src/vm/ssh.rs` line 36 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/85#-NZe_VrlC2OGb2AWs2lu:-NZfjAbV1-MfOLDy1WAH:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/2d81a53fa4b2382b978610a6f72c62a53356ceec/test-manager/src/vm/ssh.rs#L36)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This function isn't asynchronous. It would probably make sense to spawn a blocking task here or at the call site.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-06 18:07 UTC, dlon requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/85)* status: all files reviewed, 4 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`test-manager/src/vm/ssh.rs` line 7 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/85#-NZgJR0N0S4bc9SWObvc:-NZgJR0N0S4bc9SWObvd:b5ln17b) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/f0f4f03c52f2fd2e46cd35a81d4bf619d7a5f85b/test-manager/src/vm/ssh.rs#L7)):*
> ```XML
> use std::net::{IpAddr, SocketAddr, TcpStream};
> 
> pub struct SSHCredentials {
> ```

Nit: Does this struct provide any value?
___
*[`test-manager/src/vm/ssh.rs` line 38 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/85#-NZgLNJb1hXBlgLmr3KC:-NZgLNJb1hXBlgLmr3KD:b-ri3ew0) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/f0f4f03c52f2fd2e46cd35a81d4bf619d7a5f85b/test-manager/src/vm/ssh.rs#L38)):*
> ```XML
>     /// Default `ssh` port.
>     fn port() -> u16 {
>         22
> ```

Nit: It might be nicer to define a constant for this.
___
*[`test-manager/src/vm/update.rs` line 7 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/85#-NZgJBzf9hksp2d3hHh5:-NZgJBzf9hksp2d3hHh6:b-2ct6qs) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/f0f4f03c52f2fd2e46cd35a81d4bf619d7a5f85b/test-manager/src/vm/update.rs#L7)):*
> ```XML
> 
> #[derive(Debug)]
> pub enum Update {
> ```

Nit: `UpdateResult` would make this slightly more readable.
___
*[`test-manager/src/vm/update.rs` line 13 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/85#-NZgM2ad8eCSeQrg3n9A:-NZgM2ad8eCSeQrg3n9B:b-9guq1b) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/f0f4f03c52f2fd2e46cd35a81d4bf619d7a5f85b/test-manager/src/vm/update.rs#L13)):*
> ```XML
> 
> pub async fn packages(config: &VmConfig, instance: &dyn super::VmInstance) -> Result<Update> {
>     if Provisioner::Noop == config.provisioner {
> ```

`config.provisioner != Provisioner::Ssh` would make more sense here, when I think about it. Or even

```
match config.provisioner {
    Provisioner::Noop => return Ok(Update::Nothing),
    Provisioner::Ssh => (),
}
```

to prevent it from compiling as is if a new variant is added.

Even though these are currently equivalent, it's possible that we'll add more variants.
___
*[`test-manager/src/vm/update.rs` line 69 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/85#-NZgKAmYC1wVWutfRZmG:-NZgKAmZ8B_0-9Y4v3pa:bqns1ct) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/f0f4f03c52f2fd2e46cd35a81d4bf619d7a5f85b/test-manager/src/vm/update.rs#L69)):*
> ```XML
>             Update::Success(commands) => commands
>                 .iter()
>                 .try_for_each(|output| write!(formatter, "{}", output)),
> ```

Nit: `.try_for_each(|output| formatter.write_str(output))` gives you the same thing without a format string


<!-- Sent from Reviewable.io -->

2023-07-07 07:26 UTC, MarkusPettersson98 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/85)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`test-manager/src/vm/ssh.rs` line 7 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/85#-NZgJR0N0S4bc9SWObvc:-NZjE2lLDCtZaZN4V-D6:b-bmsgv0) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/f0f4f03c52f2fd2e46cd35a81d4bf619d7a5f85b/test-manager/src/vm/ssh.rs#L7)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nit: Does this struct provide any value?
</blockquote></details>

Not really, except adding more types. :ghost: 
___
*[`test-manager/src/vm/update.rs` line 13 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/85#-NZgM2ad8eCSeQrg3n9A:-NZjDaq0DIpXqRBqPUn9:bt6if67) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/f0f4f03c52f2fd2e46cd35a81d4bf619d7a5f85b/test-manager/src/vm/update.rs#L13)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

`config.provisioner != Provisioner::Ssh` would make more sense here, when I think about it. Or even

```
match config.provisioner {
    Provisioner::Noop => return Ok(Update::Nothing),
    Provisioner::Ssh => (),
}
```

to prevent it from compiling as is if a new variant is added.

Even though these are currently equivalent, it's possible that we'll add more variants.
</blockquote></details>

Since the update code is only written for the SSH use case, I think it would be confusing to break it if another provisioner was added. What's your opinion? :)


<!-- Sent from Reviewable.io -->

2023-07-07 07:35 UTC, MarkusPettersson98 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/85)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`test-manager/src/vm/update.rs` line 7 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/85#-NZgJBzf9hksp2d3hHh5:-NZjFN5V6143njHyVXuD:b-s9nn4x) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/f0f4f03c52f2fd2e46cd35a81d4bf619d7a5f85b/test-manager/src/vm/update.rs#L7)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nit: `UpdateResult` would make this slightly more readable.
</blockquote></details>

I disagree, rather I think the variant `Success` is confusing. My initial thought was that this would named something along the lines of `Packages`, and it would be populated with just that: a list of packages that were successfully updated. To do this well, we would have to parse a bunch of package manager's output, which is out of scope IMO. so I just lumped together the entire output of a string of commands instead.

I think that the `Result<..>` type conveys well enough the result of the update command (whether it succeeded or not), and that the `Update` type should convey what was updated. Before committing to any change, I would like to hear what you think about this proposed semantic :blush:


<!-- Sent from Reviewable.io -->

2023-07-07 08:42 UTC, dlon approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/85)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MarkusPettersson98)

___
*[`test-manager/src/vm/update.rs` line 7 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/85#-NZgJBzf9hksp2d3hHh5:-NZjUmTb44S8cbmLVSsL:b-419268) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/f0f4f03c52f2fd2e46cd35a81d4bf619d7a5f85b/test-manager/src/vm/update.rs#L7)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I think that that makes sense. I will not bikeshed further. `Update` is pretty clear! :slightly_smiling_face: 
</blockquote></details>

As for your second point, would it not make sense to just save the command line, the whole output, and print it in the test-manager afterwards? It might be especially useful to do this if the update fails. Currently, we don't save anything in that case, right?

We probably don't know the exact packages that were updated if we just run `apt upgrade`, etc. Is parsing that output really worth it?


<!-- Sent from Reviewable.io -->

2023-07-07 09:45 UTC, MarkusPettersson98 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/85)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @dlon)

___
*[`test-manager/src/vm/update.rs` line 7 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/85#-NZgJBzf9hksp2d3hHh5:-NZjhprD33_J3KtpQveT:b-1j0qsr) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/f0f4f03c52f2fd2e46cd35a81d4bf619d7a5f85b/test-manager/src/vm/update.rs#L7)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

As for your second point, would it not make sense to just save the command line, the whole output, and print it in the test-manager afterwards? It might be especially useful to do this if the update fails. Currently, we don't save anything in that case, right?

We probably don't know the exact packages that were updated if we just run `apt upgrade`, etc. Is parsing that output really worth it?
</blockquote></details>

If the update command fails, I would expect `ssh2::channel::exec` to propagate that as an `Error`, in which case we will print it eventually. But no, it is not stored in any of the `Update` variants atm :blush:
___
*[`test-manager/src/vm/update.rs` line 13 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/85#-NZgM2ad8eCSeQrg3n9A:-NZjgv83DRc0UuYYm7N0:b-1l0pjj) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/f0f4f03c52f2fd2e46cd35a81d4bf619d7a5f85b/test-manager/src/vm/update.rs#L13)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I think the opposite! Making this code not compile when adding another provisioner would make it impossible miss that this code will only work for SSH, and force you to make a decision about it.

But I also think that a simple if statement is less ugly, so I'm fine with this. :+1: 
</blockquote></details>

In that case, I am down for making this a compile error in case we add another provisioner :thumbsup: 


<!-- Sent from Reviewable.io -->

2023-07-07 13:39 UTC, dlon approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/85)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MarkusPettersson98)



<!-- Sent from Reviewable.io -->

2023-07-07 19:50 UTC, dlon approved these changes
> Reviewed 1 of 4 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/85)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MarkusPettersson98)



<!-- Sent from Reviewable.io -->

2023-07-07 19:54 UTC, merged