Implement a generic connection check strategy
mullvad/mullvadvpn-app-tests pull request #87
Opened 2023-07-07 11:30 UTC by MarkusPettersson98

As part of our automated tests, we want to assure that the internet is reachable through the VPN tunnel. To verify connectivity, we can request internet resources which are not the currently connected relay. Also, try something more elaborate than a ping (i.e. check for HTTP `200` from `am.i.mullvad.net`).

This is prone to network failures, which is why we retry each request 3 times before we consider it a failure.

2023-07-07 14:01 UTC, dlon requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`test-manager/src/tests/helpers.rs` line 342 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87#-NZkdaBJ-_AaaPBaUt8J:-NZkdaBJ-_AaaPBaUt8K:br6ietn) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/38a29927b9de8ae843e339df9dba017f85b82594/test-manager/src/tests/helpers.rs#L342)):*
> ```XML
> pub async fn geoip_lookup_with_retries(_rpc: ServiceClient) -> Result<AmIMullvad, Error> {
>     const MAX_ATTEMPTS: u8 = 5;
>     http_get_with_retries(&TEST_CONFIG.mullvad_host, Some(MAX_ATTEMPTS))
> ```

This seems to be making the HTTP request directly from `test-manager`. The replaced function made the HTTP request inside the VM, which is presumably what we want.


<!-- Sent from Reviewable.io -->

2023-07-10 08:25 UTC, MarkusPettersson98 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`test-manager/src/tests/helpers.rs` line 342 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87#-NZkdaBJ-_AaaPBaUt8J:-NZyZBxO-yL-TSKyE0ie:bful2bo) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/38a29927b9de8ae843e339df9dba017f85b82594/test-manager/src/tests/helpers.rs#L342)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This seems to be making the HTTP request directly from `test-manager`. The replaced command made the HTTP request inside the VM, which is presumably what we want.
</blockquote></details>

Of course, that has to be addressed. Reverted to the old implementation of `geoip_lookup_with_retries` for now :blush: 


<!-- Sent from Reviewable.io -->

2023-07-10 13:06 UTC, dlon requested changes
> Reviewed 1 of 2 files at r1, 3 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87)* status: all files reviewed, 7 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`test-manager/src/tests/tunnel.rs` line 71 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87#-NZztVFb7FmYH6nvxceO:-NZztVFb7FmYH6nvxceP:b8zg8t5) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/be70dfc0ed75fdfd58243534484ca25404b57d71/test-manager/src/tests/tunnel.rs#L71)):*
> ```XML
> 
>         //
>         // Send traffic through the tunnel
> ```

The comment doesn't describe why we're doing this.
___
*[`test-manager/src/tests/tunnel.rs` line 75 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87#-NZztHsxA-tjWfUVcrxZ:-NZztHsxA-tjWfUVcrx_:b3kzfqm) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/be70dfc0ed75fdfd58243534484ca25404b57d71/test-manager/src/tests/tunnel.rs#L75)):*
> ```XML
> 
>         log::info!("Sending traffic inside tunnel");
>         geoip_lookup_with_retries(&rpc).await.unwrap();
> ```

Do we not have to verify that the result is sane as well?
___
*[`test-manager/src/tests/tunnel.rs` line 563 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87#-NZztNreC5xpi8wHrX81:-NZztNreC5xpi8wHrX82:b8zg8t5) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/be70dfc0ed75fdfd58243534484ca25404b57d71/test-manager/src/tests/tunnel.rs#L563)):*
> ```XML
> 
>     //
>     // Send traffic through the tunnel
> ```

The comment doesn't describe why we're doing this.
___
*[`test-manager/src/tests/tunnel.rs` line 567 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87#-NZztN516ZSyieodeAsb:-NZztN516ZSyieodeAsc:b3kzfqm) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/be70dfc0ed75fdfd58243534484ca25404b57d71/test-manager/src/tests/tunnel.rs#L567)):*
> ```XML
> 
>     log::info!("Sending traffic inside tunnel");
>     geoip_lookup_with_retries(&rpc).await.unwrap();
> ```

Do we not have to verify that the result is sane as well?
___
*[`test-manager/src/tests/tunnel.rs` line 645 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87#-NZztp2489Q_7-_nLKYH:-NZztp2489Q_7-_nLKYI:b8zg8t5) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/be70dfc0ed75fdfd58243534484ca25404b57d71/test-manager/src/tests/tunnel.rs#L645)):*
> ```XML
> 
>     //
>     // Send traffic through the tunnel
> ```

The comment doesn't describe why we're doing this.
___
*[`test-manager/src/tests/tunnel.rs` line 649 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87#-NZzttTsE1yF2sMf38Z_:-NZzttTsE1yF2sMf38Za:b3kzfqm) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/be70dfc0ed75fdfd58243534484ca25404b57d71/test-manager/src/tests/tunnel.rs#L649)):*
> ```XML
> 
>     log::info!("Sending traffic inside tunnel");
>     geoip_lookup_with_retries(&rpc).await.unwrap();
> ```

Do we not have to verify that the result is sane as well?
___
*[`test-manager/src/tests/tunnel_state.rs` line 352 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87#-NZzu04E0SVETdEeOpa2:-NZzu04E0SVETdEeOpa3:b3kzfqm) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/be70dfc0ed75fdfd58243534484ca25404b57d71/test-manager/src/tests/tunnel_state.rs#L352)):*
> ```XML
> 
>     log::info!("Sending traffic inside tunnel");
>     geoip_lookup_with_retries(&rpc).await.unwrap();
> ```

Do we not have to verify that the result is sane as well?


<!-- Sent from Reviewable.io -->

2023-07-10 13:31 UTC, MarkusPettersson98 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87)* status: 5 of 7 files reviewed, 7 unresolved discussions (waiting on @dlon)

___
*[`test-manager/src/tests/tunnel.rs` line 71 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87#-NZztVFb7FmYH6nvxceO:-NZzyvh24cISn3WsjSIW:b-m1ydrk) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/be70dfc0ed75fdfd58243534484ca25404b57d71/test-manager/src/tests/tunnel.rs#L71)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

The comment doesn't describe why we're doing this.
</blockquote></details>

Added some more text to the comment. Didn't really find any inspiration except for function-level comments, but please let me know what you think. :)
___
*[`test-manager/src/tests/tunnel.rs` line 75 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87#-NZztHsxA-tjWfUVcrxZ:-NZzybE9C-qv5GDkMDWw:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/be70dfc0ed75fdfd58243534484ca25404b57d71/test-manager/src/tests/tunnel.rs#L75)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Do we not have to verify that the result is sane as well?
</blockquote></details>

Done.
___
*[`test-manager/src/tests/tunnel.rs` line 563 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87#-NZztNreC5xpi8wHrX81:-N_--18x1UFT1DNl3PE6:bb6uiqt) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/be70dfc0ed75fdfd58243534484ca25404b57d71/test-manager/src/tests/tunnel.rs#L563)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

The comment doesn't describe why we're doing this.
</blockquote></details>

Dito
___
*[`test-manager/src/tests/tunnel.rs` line 567 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87#-NZztN516ZSyieodeAsb:-NZzyl5Z3BORPKbHfsa5:bs7wumx) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/be70dfc0ed75fdfd58243534484ca25404b57d71/test-manager/src/tests/tunnel.rs#L567)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Do we not have to verify that the result is sane as well?
</blockquote></details>

Done. 
___
*[`test-manager/src/tests/tunnel.rs` line 645 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87#-NZztp2489Q_7-_nLKYH:-N_--2Gf4k5t2SnRBuH0:bb6uiqt) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/be70dfc0ed75fdfd58243534484ca25404b57d71/test-manager/src/tests/tunnel.rs#L645)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

The comment doesn't describe why we're doing this.
</blockquote></details>

Dito
___
*[`test-manager/src/tests/tunnel.rs` line 649 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87#-NZzttTsE1yF2sMf38Z_:-NZzynzE7a6P-atyec6Z:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/be70dfc0ed75fdfd58243534484ca25404b57d71/test-manager/src/tests/tunnel.rs#L649)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Do we not have to verify that the result is sane as well?
</blockquote></details>

Done.
___
*[`test-manager/src/tests/tunnel_state.rs` line 352 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87#-NZzu04E0SVETdEeOpa2:-NZzy1WE7SC0bleNiFKl:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/be70dfc0ed75fdfd58243534484ca25404b57d71/test-manager/src/tests/tunnel_state.rs#L352)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Do we not have to verify that the result is sane as well?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-10 15:37 UTC, dlon approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87)* status: all files reviewed, 2 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`test-manager/src/tests/tunnel.rs` line 27 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87#-N_-Qzdr1Vig0TuD6HLR:-N_-Qzdr1Vig0TuD6HLS:b2gpcps) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/be70dfc0ed75fdfd58243534484ca25404b57d71/test-manager/src/tests/tunnel.rs#L27)):*
> ```XML
> /// This test fails if a working tunnel cannot be set up.
> #[test_function]
> pub async fn test_openvpn_tunnel(
> ```

Could we do the same thing for `test_wireguard_tunnel`?
___
*[`test-manager/src/tests/tunnel.rs` line 71 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87#-NZztVFb7FmYH6nvxceO:-N_-PTiCDVHz5COPb4Wi:boz47zz) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/be70dfc0ed75fdfd58243534484ca25404b57d71/test-manager/src/tests/tunnel.rs#L71)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Added some more text to the comment. Didn't really find any inspiration except for function-level comments, but please let me know what you think. :)
</blockquote></details>

Much better. :)
___
*[`test-manager/src/tests/tunnel_state.rs` line 281 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87#-N_-Ppva374qSdC-FUPw:-N_-Ppva374qSdC-FUPx:bcxbz5a) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/7df2f65ac6cb35070cffa7846445674346c16d07/test-manager/src/tests/tunnel_state.rs#L281)):*
> ```XML
>     log::info!("Select relay");
> 
>     let entry_hostname: String = String::from("se-got-wg-001");
> ```

Nit: This could be `const` (`&str`). Also, you don't need to specify the type explicitly with `let` here.
___
*[`test-manager/src/tests/tunnel_state.rs` line 352 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87#-N_-QOWb9gG7rbk_1n4P:-N_-QOWb9gG7rbk_1n4Q:b-9xksjd) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/7df2f65ac6cb35070cffa7846445674346c16d07/test-manager/src/tests/tunnel_state.rs#L352)):*
> ```XML
>     let geoip_lookup = geoip_lookup_with_retries(&rpc).await.unwrap();
>     assert!(geoip_lookup.mullvad_exit_ip, "Exit ip is not from Mullvad");
>     assert_eq!(geoip_lookup.mullvad_exit_ip_hostname, entry_hostname);
> ```

Could we rename `entry_hostname` to `exit_hostname`? I mean, it's technically both in this case, but this feels a bit confusing.


<!-- Sent from Reviewable.io -->

2023-07-10 15:49 UTC, dlon approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87)* status: all files reviewed, 3 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`test-manager/src/tests/tunnel_state.rs` line 348 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87#-N_-Tx4z6Q6LLf6vjBhv:-N_-Tx4z6Q6LLf6vjBhw:bxe0jgo) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/7df2f65ac6cb35070cffa7846445674346c16d07/test-manager/src/tests/tunnel_state.rs#L348)):*
> ```XML
>     );
> 
>     // Send traffic through the tunnel to sanity check that the internet is reachable.
> ```

I think that we should replace `ping_with_timeout` in `test_lockdown` and `test_udp2tcp_tunnel` with the same thing.


<!-- Sent from Reviewable.io -->

2023-07-11 07:34 UTC, MarkusPettersson98 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`test-manager/src/tests/tunnel_state.rs` line 352 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87#-N_-QOWb9gG7rbk_1n4P:-N_2ridH-CtPSmPSwt-p:bqw6q9) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/7df2f65ac6cb35070cffa7846445674346c16d07/test-manager/src/tests/tunnel_state.rs#L352)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Could we rename `entry_hostname` to `exit_hostname`? I mean, it's technically both in this case, but this feels a bit confusing.
</blockquote></details>

I renamed it to `RELAY_HOSTNAME` as to not confuse with the entry/exit terminology :blush: 


<!-- Sent from Reviewable.io -->

2023-07-11 07:38 UTC, dlon approved these changes
> Reviewed 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MarkusPettersson98)

___
*[`test-manager/src/tests/tunnel_state.rs` line 352 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87#-N_-QOWb9gG7rbk_1n4P:-N_2sIbu5qBH2IJA02NZ:b-83sjoh) ([raw file](https://github.com/mullvad/mullvadvpn-app-tests/blob/7df2f65ac6cb35070cffa7846445674346c16d07/test-manager/src/tests/tunnel_state.rs#L352)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

I renamed it to `RELAY_HOSTNAME` as to not confuse with the entry/exit terminology :blush: 
</blockquote></details>

Nice!


<!-- Sent from Reviewable.io -->

2023-07-11 09:07 UTC, dlon approved these changes
> Reviewed 8 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MarkusPettersson98)



<!-- Sent from Reviewable.io -->

2023-07-11 12:06 UTC, merged